name: Tests with io_uring

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.0', '3.1', 'head']

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true # 'bundle install' and cache
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Show Linux kernel version
      run: uname -a
    - name: Compile C-extension
      run: bundle exec rake compile
    - name: Run tests
      run:  bundle exec rake test
